name: ci-cd-pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  lint_and_test:
    runs-on: ubuntu-22.04
    container: python:3.9-slim
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --all-extras
      - name: Formatting
        if: always()
        run: poetry run black --check scamlgp/ tests/
      - name: Linting
        if: always()
        run: poetry run ruff check scamlgp/ tests/ 
      - name: Run tests
        if: always()
        run: poetry run pytest tests/
